# Project Information
site_name: 白阁文库
site_keywords: 白泽Sec,白阁文库,白阁wiki,漏洞复现,漏洞利用,漏洞,靶场
site_description: 白泽Sec - 专注于信息安全领域的技术研究。白阁文库是白泽Sec团队维护的一个漏洞POC和EXP披露以及漏洞复现的开源项目，欢迎各位表哥访问白阁文库并提出宝贵建议。
site_author: BaizeSec Team
site_url: https://wiki.bylibrary.cn

# Repository
repo_name: 'BaizeSec/bylibrary'
repo_url: 'https://github.com/BaizeSec/bylibrary'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 - 2020 BaizeSec Team'


# Theme
theme:
  name: 'material'
  language: 'zh'
  # 禁止加载 Google 字体
  font: false
  palette:
    primary: 'white'
    accent: 'red'
    scheme: preference
  icon:
    logo: 'material/school'


markdown_extensions:
  - toc: # 锚点
      permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BaizeSec
      name: BaizeSec