# Project Information
site_name: 白阁文库
site_description: 白阁文库,白泽Sec
site_author: BaizeSec Team
site_url: http://wiki.bylibrary.cn

# Repository
repo_name: 'BaizeSec/bylibrary'
repo_url: 'https://github.com/BaizeSec/bylibrary'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 - 2020 BaizeSec Team'


# Theme
theme:
  name: 'material'
  language: 'zh'
  # 禁止加载 Google 字体
  font: false
  palette:
    primary: 'white'
    accent: 'red'
    scheme: preference
  icon:
    logo: 'material/school'


markdown_extensions:
  - toc: # 锚点
      permalink: true